pipelines:
  - name: test
    sources:
      - type: file
        name: mylog
        paths:
          - "/var/log/nginx/*.log"
    sink:
      type: elasticsearch
      hosts: ["127.0.0.1:9200"]
      username: "elastic"
      password: "pas3@132"
      #caCertPath: certs/ca/ca.crt
      index: "${+YYYY.MM.DD}"
    interceptors:
      - type: transformer
        actions:
          - action: regex(body)
            pattern: (?<ip>\S+) (?<id>\S+) (?<u>\S+) (?<time>\[.*?\]) (?<url>\".*?\") (?<status>\S+) (?<size>\S+)

